apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: remoteservers.fadk8sctrl.fortinet.com
spec:
  preserveUnknownFields: false
  group: fadk8sctrl.fortinet.com
  names:
    kind: RemoteServer
    plural: remoteservers
    singular: remoteserver
    shortNames:
      - glbrs
  scope: Namespaced
  versions:
    -
      name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: SERVERTYPE
          type: string
          jsonPath: .spec.serverType
        - name: STATUS
          type: string
          jsonPath: .status.status
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - serverType
                - dataCenter
                - vdom
              properties:
                serverType:
                  type: string
                  enum: [ FortiADC-SLB, Generic-Host, SDN-Connector ]
                  default: FortiADC-SLB
                authType:
                  type: string
                  enum: [ none, TCP_MD5SIG, auth_verify ]
                  default: none
                authKey:
                  type: string
                  pattern: '^[a-zA-Z]+([A-z0-9-_+])*([A-z0-9])$'
                addressType:
                  type: string
                  enum: [ ipv4, ipv6 ]
                  default: ipv4
                ip:
                  type: string
                  pattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])|(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))$'
                port:
                  type: integer
                  minimum: 1
                  maximum: 65535
                  default: 5858
                dataCenter:
                  type: object
                  required:
                    - name
                    - location
                  properties:
                    name:
                      type: string
                      pattern: '^[a-zA-Z]+([A-z0-9-_+])*([A-z0-9])$'
                    location:
                      type: string
                      pattern: '^[a-zA-Z]+'
                    description:
                      type: string
                      pattern: '^[a-zA-Z0-9_]+'
                autoSync:
                  type: string
                  enum: [ enable, disable ]
                  default: disable
                healthCheckList:
                  type: string
                  pattern: '^[a-zA-Z]+([A-z0-9-_+])*([A-z0-9])$'
                vdom:
                  type: string
                  pattern: '^[a-zA-Z]+[-A-z0-9_.]+$'
                  x-kubernetes-validations:
                    - message: "Vdom of Remote Server can not be changed."
                      rule: self == oldSelf
            status:
              type: object
              properties:
                status:
                  type: string
                  default: Pending
      subresources:
        status: {}
