apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: datacenters.fadk8sctrl.fortinet.com
  annotations:
    "helm.sh/resource-policy": keep
spec:
  preserveUnknownFields: false
  group: fadk8sctrl.fortinet.com
  names:
    kind: DataCenter
    plural: datacenters
    singular: datacenter
    shortNames:
      - dc
  scope: Namespaced
  versions:
    -
      name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: LOCATION
          type: string
          jsonPath: .spec.location
        - name: STATUS
          type: string
          jsonPath: .status.status
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - location
                - vdom
              properties:
                location:
                  type: string
                  pattern: '^[a-zA-Z]+([A-z0-9-_+])*([A-z0-9])$'
                  default: ZZ
                description:
                  type: string
                  pattern: '^[a-zA-Z]+([A-z0-9-_+])*([A-z0-9])$'
                vdom:
                  type: string
                  pattern: '^[a-zA-Z]+[-A-z0-9_.]+$'
                  x-kubernetes-validations:
                    - message: "Vdom of Data Center can not be changed."
                      rule: self == oldSelf
            status:
              type: object
              properties:
                status:
                  type: string
                  default: Pending
      subresources:
        status: {}
