apiVersion: fadk8sctrl.fortinet.com/v1alpha1
kind: DataCenter
metadata:
  name: minimal-datacenter
  annotations: {
    "fortiadc-ip" : "172.23.133.185",
    "fortiadc-login" : "fad-login",
    "fortiadc-ctrl-log" : "enable",
    "fortiadc-admin-port": "443"
   }
spec:
  location: ZZ
  description: test
  vdom: root
