apiVersion: v1
kind: Pod
metadata:
  name: udp-echo-server
  labels:
    app: udp-echo-server
spec:
  automountServiceAccountToken: false
  containers:
    - name: socat
      image: alpine/socat
      args: ["-v", "UDP-RECVFROM:9999,fork", "EXEC:/bin/cat"]
      ports:
        - containerPort: 9999
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: udp-echo-service
  annotations: {
    "health-check-ctrl" : "enable",
    "health-check-relation" : "OR",
    "health-check-list" : "LB_HLTHCK_ICMP",
    "real-server-ssl-profile" : "NONE",
    "overlay_tunnel" : "k8s"
  }
spec:
  selector:
    app: udp-echo-server
  type: ClusterIP
  ports:
  - name: udp
    protocol: UDP
    port: 9999
    targetPort: 9999

